common:
    loglevel: info
    secret_key: 7jC9THnLDjPOldE7qPPajmR1qNPwmtUarOxRMmhHzGmSLgIvy20xTjcpyduw7gbP

development:
    storage: local
    storage_path: /data/registry

production:
    storage: local
    storage_path: /data/registry